---
- name: create dracula dir
  ansible.builtin.file:
    path: "{{ dracula_dir }}"
    state: directory
    owner: "{{ ansible_user }}"
    group: "{{ ansible_user }}"
    mode: "0755"

- name: clone dracula xresources
  git:
    repo: "{{ dracula_xresources_url }}"
    dest: "{{ dracula_xresources_path }}"

- name: clone dracula vim
  git:
    repo: "{{ dracula_vim_url }}"
    dest: "{{ dracula_vim_path }}"
